default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: '<%= ENV['DATABASE_PASSWORD'] %>'

development:
  <<: *default
  database: Rails_Recipe_development
  username: postgres
  password: '<%= ENV['DATABASE_PASSWORD'] %>'
  host: localhost
  port: 5432

test:
  <<: *default
  database: Rails_Recipe_test

production:
  <<: *default
  database: Rails_Recipe_production
  username: Recipe
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
